### PR TITLE
Use 0.12 terraform sdk

### PR DESCRIPTION
**Pull request by rporres**
```
go get github.com/hashicorp/terraform@v0.12.0
go mod tidy
rm -r vendor/
go mod vendor
```

### CODE REVIEW

**Comment by remyleone** [comment]
@jerome-quere @quentinbrosse

**Comment by remyleone** [comment]
https://github.com/terraform-providers/terraform-provider-scaleway/pull/127

**Comment by meyskens** [comment]
This PR now also includes a lot of patches for the acceptance tests as they were depending on our account before

**Comment by rporres** [comment]
Changes look great, @meyskens

**Pull request merged**
